name: npm registry
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "9.15.9"
    - name: pnpm install
      shell: bash
      run: |
        pnpm i -g verdaccio
        git config user.name github-actions
        git config user.email github-actions@github.com
        verdaccio & (mkdir -p .temp && cd .temp && bash ../npm-install.sh && cd .. && bash ./npm-make-registry.sh)
    - name: Archive Release packages
      shell: bash
      run: |
        date=$(date '+%Y%m%d%H%M%S')
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx -m0=LZMA2 -v40m verdaccio-packages-$date.7z packages/ -x!node_modules
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          verdaccio-packages*
        tag_name: ${{ github.event.inputs.tags }}
  build-ubuntu:
    runs-on: ubuntu-latest
    needs: build-windows
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "9.1.1"
    - name: pnpm install
      shell: bash
      run: |
        pnpm i -g verdaccio
        git config user.name github-actions
        git config user.email github-actions@github.com
        verdaccio & (mkdir -p .temp && cd .temp && bash ../npm-install.sh && cd .. && bash ./npm-make-registry.sh)
    - name: Archive Release packages
      shell: bash
      run: |
        date=$(date '+%Y%m%d%H%M%S')
        7z a -t7z -mx -m0=LZMA2 -v40m verdaccio-packages-$date.7z packages/ -x!node_modules
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          verdaccio-packages*
        tag_name: ${{ github.event.inputs.tags }}
